name: Test build kernel

on:
  push:
    branches:
      Grass-Unified
  pull_request:
    branches:
      Grass-Unified
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - device: a51
          - device: m30s
          - device: m21
          - device: m31
          - device: m31s
          - device: f41
    name: "🚧 Build for ${{matrix.device}}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install packages & setup
        run: |
          sudo apt update
          wget https://github.com/XSans0/WeebX-Clang/releases/download/WeebX-Clang-19.0.0git-release/WeebX-Clang-19.0.0git.tar.gz -O "weebx-clang.tar.gz"
          rm -rf toolchain && mkdir toolchain && tar -xvf weebx-clang.tar.gz -C clang && rm -rf weebx-clang.tar.gz
          sudo apt install bison flex libssl-dev

      - name: Run build
        run: |
          python build_kernel.py --aosp --target=${{matrix.device}}

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: GrassKernel_${{matrix.device}}.zip
          path: scripts/packaging/Grass*

